<table>
    <tbody>
    @foreach($excelReports as $excelReport)
        <tr>
            <th>{{ $excelReport->SECT_ID }} </th>
            <th>{{ $excelReport->SECT_NAME }} </th>
            <th>{{ $excelReport->LINK_ID }} </th>
            <th>{{ $excelReport->LINK_NAME }} </th>
            <th>{{ $excelReport->SPEED_FLOW }} </th>
            <th>{{ $excelReport->TRAF_FLOW }} </th>
            <th>{{ $excelReport->ACC_CLASS }} </th>
            <th>{{ $excelReport->ROAD_CLASS }} </th>
            <th>{{ $excelReport->CLIM_ZONE }} </th>
            <th>{{ $excelReport->SURF_CLASS }} </th>
            <th>{{ $excelReport->LENGTH }} </th>
            <th>{{ $excelReport->CWAY_WIDTH }} </th>
            <th>{{ $excelReport->SHLD_WIDTH }} </th>
            <th>{{ $excelReport->MT_AADT }} </th>
            <th>{{ $excelReport->NM_AADT }} </th>
            <th>{{ $excelReport->AADT_YEAR }} </th>
            <th>{{ $excelReport->DIRECTION }} </th>
            <th>{{ $excelReport->RF }} </th>
            <th>{{ $excelReport->NUM_RFS }} </th>
            <th>{{ $excelReport->SUPERELEV }} </th>
            <th>{{ $excelReport->CURVATURE }} </th>
            <th>{{ $excelReport->SIGM_ADRAL }} </th>
            <th>{{ $excelReport->SPEED_LIM }} </th>
            <th>{{ $excelReport->ENFORCEMNT }} </th>
            <th>{{ $excelReport->XNMT }} </th>
            <th>{{ $excelReport->XMT }} </th>
            <th>{{ $excelReport->XFRI }} </th>
            <th>{{ $excelReport->HSNEW }} </th>
            <th>{{ $excelReport->HSOLD }} </th>
            <th>{{ $excelReport->HBASE }} </th>
            <th>{{ $excelReport->RES_MODULU }} </th>
            <th>{{ $excelReport->REL_COMPCT }} </th>
            <th>{{ $excelReport->SNP_DERIVE }} </th>
            <th>{{ $excelReport->SN }} </th>
            <th>{{ $excelReport->CBR }} </th>
            <th>{{ $excelReport->SNP_DRY }} </th>
            <th>{{ $excelReport->D0 }} </th>
            <th>{{ $excelReport->BENKEL_DEF }} </th>
            <th>{{ $excelReport->SURF_STREN }} </th>
            <th>{{ $excelReport->BASE_STREN }} </th>
            <th>{{ $excelReport->SUBB_STREN }} </th>
            <th>{{ $excelReport->HSUBBASE }} </th>
            <th>{{ $excelReport->SURF_THICK }} </th>
            <th>{{ $excelReport->SLAB_LENTH }} </th>
            <th>{{ $excelReport->BASE_THICK }} </th>
            <th>{{ $excelReport->BASE_MODUL }} </th>
            <th>{{ $excelReport->CNSTR_YEAR }} </th>
            <th>{{ $excelReport->SUBG_MATRL }} </th>
            <th>{{ $excelReport->COMPMETHOD }} </th>
            <th>{{ $excelReport->COND_YEAR }} </th>
            <th>{{ $excelReport->ROUGHNESS }} </th>
            <th>{{ $excelReport->CRACKS_ACA }} </th>
            <th>{{ $excelReport->CRACKS_ACW }} </th>
            <th>{{ $excelReport->CRACKS_ACT }} </th>
            <th>{{ $excelReport->RAVEL_AREA }} </th>
            <th>{{ $excelReport->PHOLE_NUM }} </th>
            <th>{{ $excelReport->EDGEBREAK }} </th>
            <th>{{ $excelReport->RUT_DEPTH }} </th>
            <th>{{ $excelReport->RUTDEPTH_SD }} </th>
            <th>{{ $excelReport->TEXT_DEPTH }} </th>
            <th>{{ $excelReport->SKIDRESIST }} </th>
            <th>{{ $excelReport->DRAIN_COND }} </th>
            <th>{{ $excelReport->FAULTING }} </th>
            <th>{{ $excelReport->SPALL_JNTS }} </th>
            <th>{{ $excelReport->CRACKSLABS }} </th>
            <th>{{ $excelReport->DETERCRACK }} </th>
            <th>{{ $excelReport->FAILURESKM }} </th>
            <th>{{ $excelReport->GRAV_THICK }} </th>
            <th>{{ $excelReport->LAST_CONST }} </th>
            <th>{{ $excelReport->LAST_SURF }} </th>
            <th>{{ $excelReport->LAST_PRVNT }} </th>
            <th>{{ $excelReport->LAST_REHAB }} </th>
            <th>{{ $excelReport->PREV_ACA }} </th>
            <th>{{ $excelReport->PREV_ACW }} </th>
            <th>{{ $excelReport->PREV_NCT }} </th>
            <th>{{ $excelReport->LASTGRAVEL }} </th>
            <th>{{ $excelReport->DRAIN_TYPE }} </th>
            <th>{{ $excelReport->ALTITUDE }} </th>
            <th>{{ $excelReport->SHOULDTYPE }} </th>
            <th>{{ $excelReport->WIDN_WIDTH }} </th>
            <th>{{ $excelReport->EDGEDRAINS }} </th>
            <th>{{ $excelReport->NMT_SEPAR }} </th>
            <th>{{ $excelReport->NMTLANES }} </th>
            <th>{{ $excelReport->ELANES }} </th>
            <th>{{ $excelReport->CALIB_ITEM }} </th>
            <th>{{ $excelReport->REPCOST }} </th>
            <th>{{ $excelReport->CONDBASED }} </th>
            <th>{{ $excelReport->INIROUGH }} </th>
            <th>{{ $excelReport->TERROUGH }} </th>
            <th>{{ $excelReport->RDFOSBGR_P }} </th>
            <th>{{ $excelReport->RDPVLA_PRR }} </th>
            <th>{{ $excelReport->FTCYCLE_PR }} </th>
            <th>{{ $excelReport->BRDGSTR_PR }} </th>
            <th>{{ $excelReport->TRFSGN_PRR }} </th>
            <th>{{ $excelReport->RDFOSBGR_R }} </th>
            <th>{{ $excelReport->RDPVLA_RES }} </th>
            <th>{{ $excelReport->FTCYCLE_RE }} </th>
            <th>{{ $excelReport->BRDGSTR_RE }} </th>
            <th>{{ $excelReport->TRFSGN_RES }} </th>
            <th>{{ $excelReport->RDFOSBGR_U }} </th>
            <th>{{ $excelReport->RDPVLA_USE }} </th>
            <th>{{ $excelReport->FTCYCLE_US }} </th>
            <th>{{ $excelReport->BRDGSTR_US }} </th>
            <th>{{ $excelReport->TRFSGN_USE }} </th>
            <th>{{ $excelReport->RDFOSBGR_A }} </th>
            <th>{{ $excelReport->RDPVLA_AGE }} </th>
            <th>{{ $excelReport->FTCYCLE_AG }} </th>
            <th>{{ $excelReport->BRDGSTR_AG }} </th>
            <th>{{ $excelReport->TRFSGN_AGE }} </th>
            <th>{{ $excelReport->COMPAGEYEA }} </th>
            <th>{{ $excelReport->USFLFEUNIT }} </th>
            <th>{{ $excelReport->ID }} </th>
        </tr>
    @endforeach
    </tbody>
</table>