<?php

namespace App\Imports;

use App\Models\Business\Roads\GeneralCharacteristicsOfTrackHdm4;
use App\Models\Business\Roads\GeneralCharacteristicsOfTrack;
use Maatwebsite\Excel\Concerns\ToModel;
use Illuminate\Database\Eloquent\Model;
use DB;

class RoadsExport implements ToModel
{
    /**
     * Generar nuevo archivo para el HDM4
     *
     * @param array $row
     *
     * @return GeneralCharacteristicsOfTrackHdm4|Model|Model[]|null
     */
    public function model(array $row)
    {
        if (isset($row[2]) && $row[2] == 'LINK_ID') {
            return new GeneralCharacteristicsOfTrackHdm4([
                'SECT_ID' => $row[0],
                'SECT_NAME' => $row[1],
                'LINK_ID' => $row[2],
                'LINK_NAME' => $row[3],
                'SPEED_FLOW' => $row[4],
                'TRAF_FLOW' => $row[5],
                'ACC_CLASS' => $row[6],
                'ROAD_CLASS' => $row[7],
                'CLIM_ZONE' => $row[8],
                'SURF_CLASS' => $row[9],
                'LENGTH' => $row[10],
                'CWAY_WIDTH' => $row[11],
                'SHLD_WIDTH' => $row[12],
                'MT_AADT' => $row[13],
                'NM_AADT' => $row[14],
                'AADT_YEAR' => $row[15],
                'DIRECTION' => $row[16],
                'RF' => $row[17],
                'NUM_RFS' => $row[18],
                'SUPERELEV' => $row[19],
                'CURVATURE' => $row[20],
                'SIGM_ADRAL' => $row[21],
                'SPEED_LIM' => $row[22],
                'ENFORCEMNT' => $row[23],
                'XNMT' => $row[24],
                'XMT' => $row[25],
                'XFRI' => $row[26],
                'HSNEW' => $row[27],
                'HSOLD' => $row[28],
                'HBASE' => $row[29],
                'RES_MODULU' => $row[30],
                'REL_COMPCT' => $row[31],
                'SNP_DERIVE' => $row[32],
                'SN' => $row[33],
                'CBR' => $row[34],
                'SNP_DRY' => $row[35],
                'D0' => $row[36],
                'BENKEL_DEF' => $row[37],
                'SURF_STREN' => $row[38],
                'BASE_STREN' => $row[39],
                'SUBB_STREN' => $row[40],
                'HSUBBASE' => $row[41],
                'SURF_THICK' => $row[42],
                'SLAB_LENTH' => $row[43],
                'BASE_THICK' => $row[44],
                'BASE_MODUL' => $row[45],
                'CNSTR_YEAR' => $row[46],
                'SUBG_MATRL' => $row[47],
                'COMPMETHOD' => $row[48],
                'COND_YEAR' => $row[49],
                'ROUGHNESS' => $row[50],
                'CRACKS_ACA' => $row[51],
                'CRACKS_ACW' => $row[52],
                'CRACKS_ACT' => $row[53],
                'RAVEL_AREA' => $row[54],
                'PHOLE_NUM' => $row[55],
                'EDGEBREAK' => $row[56],
                'RUT_DEPTH' => $row[57],
                'RUTDEPTH_SD' => $row[58],
                'TEXT_DEPTH' => $row[59],
                'SKIDRESIST' => $row[60],
                'DRAIN_COND' => $row[61],
                'FAULTING' => $row[62],
                'SPALL_JNTS' => $row[63],
                'CRACKSLABS' => $row[64],
                'DETERCRACK' => $row[65],
                'FAILURESKM' => $row[66],
                'GRAV_THICK' => $row[67],
                'LAST_CONST' => $row[68],
                'LAST_SURF' => $row[69],
                'LAST_PRVNT' => $row[70],
                'LAST_REHAB' => $row[71],
                'PREV_ACA' => $row[72],
                'PREV_ACW' => $row[73],
                'PREV_NCT' => $row[74],
                'LASTGRAVEL' => $row[75],
                'DRAIN_TYPE' => $row[76],
                'ALTITUDE' => $row[77],
                'SHOULDTYPE' => $row[78],
                'WIDN_WIDTH' => $row[79],
                'EDGEDRAINS' => $row[80],
                'NMT_SEPAR' => $row[81],
                'NMTLANES' => $row[82],
                'ELANES' => $row[83],
                'CALIB_ITEM' => $row[84],
                'REPCOST' => $row[85],
                'CONDBASED' => $row[86],
                'INIROUGH' => $row[87],
                'TERROUGH' => $row[88],
                'RDFOSBGR_P' => $row[89],
                'RDPVLA_PRR' => $row[90],
                'FTCYCLE_PR' => $row[91],
                'BRDGSTR_PR' => $row[92],
                'TRFSGN_PRR' => $row[93],
                'RDFOSBGR_R' => $row[94],
                'RDPVLA_RES' => $row[95],
                'FTCYCLE_RE' => $row[96],
                'BRDGSTR_RE' => $row[97],
                'TRFSGN_RES' => $row[98],
                'RDFOSBGR_U' => $row[99],
                'RDPVLA_USE' => $row[100],
                'FTCYCLE_US' => $row[101],
                'BRDGSTR_US' => $row[102],
                'TRFSGN_USE' => $row[103],
                'RDFOSBGR_A' => $row[104],
                'RDPVLA_AGE' => $row[105],
                'FTCYCLE_AG' => $row[106],
                'BRDGSTR_AG' => $row[107],
                'TRFSGN_AGE' => $row[108],
                'COMPAGEYEA' => $row[109],
                'USFLFEUNIT' => $row[110],
                'ID' => $row[111]
            ]);
        } else {
            $excelReports = GeneralCharacteristicsOfTrack::where('caracteristicas_generales_via.codigo', $row[2])
                ->leftJoin('caracteristicas_via', 'caracteristicas_via.codigo', '=', 'caracteristicas_generales_via.codigo')
                ->leftJoin('trafico', 'trafico.codigo', '=', 'caracteristicas_generales_via.codigo')
                ->select('caracteristicas_via.carriles', 'caracteristicas_via.longitud',
                    'caracteristicas_via.anchovi', 'trafico.Total tráfico', 'caracteristicas_via.velprom',
                    'caracteristicas_via.tsuperf',
                    DB::raw('(CASE
                        WHEN caracteristicas_via.tsuperf = "ADOQUIN" THEN "Hormigón"
                        WHEN caracteristicas_via.tsuperf = "D-T BITUMINOSO" THEN "DBT"
                        WHEN caracteristicas_via.tsuperf = "EMPEDRADO" THEN "Lastre"
                        WHEN caracteristicas_via.tsuperf = "LASTRE" THEN "Lastre"
                        WHEN caracteristicas_via.tsuperf = "MIXTO" THEN "Asfáltico"
                        WHEN caracteristicas_via.tsuperf = "PAVIMENTO FLEXIBLE" THEN "Asfáltico"
                        WHEN caracteristicas_via.tsuperf = "PAVIMENTO RIGIDO" THEN "Asfáltico"
                        WHEN caracteristicas_via.tsuperf = "SUELO NATURAL" THEN "Tierra"
                        WHEN caracteristicas_via.tsuperf = "TIERRA" THEN "Tierra"
                        END) AS calib_item')
                )
                ->orderby('trafico.gid', 'desc')
                ->orderby('caracteristicas_via.gid', 'desc')
                ->first();

            return new GeneralCharacteristicsOfTrackHdm4([
                'SECT_ID' => $row[0],
                'SECT_NAME' => $row[1],
                'LINK_ID' => $row[2],
                'LINK_NAME' => $row[3],
                'SPEED_FLOW' => ($excelReports) ? $excelReports->carriles : $row[4],
                'TRAF_FLOW' => $row[5],
                'ACC_CLASS' => $row[6],
                'ROAD_CLASS' => $row[7],
                'CLIM_ZONE' => $row[8],
                'SURF_CLASS' => $row[9],
                'LENGTH' => ($excelReports) ? $excelReports->longitud : $row[10],
                'CWAY_WIDTH' => ($excelReports) ? $excelReports->anchovi : $row[11],
                'SHLD_WIDTH' => $row[12],
                'MT_AADT' => ($excelReports) ? $excelReports->{'Total tráfico'} : $row[13],
                'NM_AADT' => $row[14],
                'AADT_YEAR' => $row[15],
                'DIRECTION' => $row[16],
                'RF' => $row[17],
                'NUM_RFS' => $row[18],
                'SUPERELEV' => $row[19],
                'CURVATURE' => $row[20],
                'SIGM_ADRAL' => $row[21],
                'SPEED_LIM' => ($excelReports) ? $excelReports->velprom : $row[22],
                'ENFORCEMNT' => $row[23],
                'XNMT' => $row[24],
                'XMT' => $row[25],
                'XFRI' => $row[26],
                'HSNEW' => $row[27],
                'HSOLD' => $row[28],
                'HBASE' => $row[29],
                'RES_MODULU' => $row[30],
                'REL_COMPCT' => $row[31],
                'SNP_DERIVE' => $row[32],
                'SN' => $row[33],
                'CBR' => $row[34],
                'SNP_DRY' => ($row[35]) ? GeneralCharacteristicsOfTrackHdm4::STATUS_TRUE : GeneralCharacteristicsOfTrackHdm4::STATUS_FALSE,
                'D0' => $row[36],
                'BENKEL_DEF' => $row[37],
                'SURF_STREN' => $row[38],
                'BASE_STREN' => $row[39],
                'SUBB_STREN' => $row[40],
                'HSUBBASE' => $row[41],
                'SURF_THICK' => $row[42],
                'SLAB_LENTH' => $row[43],
                'BASE_THICK' => $row[44],
                'BASE_MODUL' => $row[45],
                'CNSTR_YEAR' => $row[46],
                'SUBG_MATRL' => $row[47],
                'COMPMETHOD' => $row[48],
                'COND_YEAR' => $row[49],
                'ROUGHNESS' => $row[50],
                'CRACKS_ACA' => $row[51],
                'CRACKS_ACW' => $row[52],
                'CRACKS_ACT' => $row[53],
                'RAVEL_AREA' => $row[54],
                'PHOLE_NUM' => $row[55],
                'EDGEBREAK' => $row[56],
                'RUT_DEPTH' => $row[57],
                'RUTDEPTH_SD' => $row[58],
                'TEXT_DEPTH' => $row[59],
                'SKIDRESIST' => $row[60],
                'DRAIN_COND' => $row[61],
                'FAULTING' => $row[62],
                'SPALL_JNTS' => $row[63],
                'CRACKSLABS' => $row[64],
                'DETERCRACK' => $row[65],
                'FAILURESKM' => $row[66],
                'GRAV_THICK' => $row[67],
                'LAST_CONST' => $row[68],
                'LAST_SURF' => $row[69],
                'LAST_PRVNT' => $row[70],
                'LAST_REHAB' => $row[71],
                'PREV_ACA' => $row[72],
                'PREV_ACW' => $row[73],
                'PREV_NCT' => $row[74],
                'LASTGRAVEL' => $row[75],
                'DRAIN_TYPE' => $row[76],
                'ALTITUDE' => $row[77],
                'SHOULDTYPE' => $row[78],
                'WIDN_WIDTH' => $row[79],
                'EDGEDRAINS' => ($row[80]) ? GeneralCharacteristicsOfTrackHdm4::STATUS_TRUE : GeneralCharacteristicsOfTrackHdm4::STATUS_FALSE,
                'NMT_SEPAR' => ($row[81]) ? GeneralCharacteristicsOfTrackHdm4::STATUS_TRUE : GeneralCharacteristicsOfTrackHdm4::STATUS_FALSE,
                'NMTLANES' => $row[82],
                'ELANES' => $row[83],
                'CALIB_ITEM' => ($excelReports) ? $excelReports->calib_item : $row[84],
                'REPCOST' => $row[85],
                'CONDBASED' => ($row[86]) ? GeneralCharacteristicsOfTrackHdm4::STATUS_TRUE : GeneralCharacteristicsOfTrackHdm4::STATUS_FALSE,
                'INIROUGH' => $row[87],
                'TERROUGH' => $row[88],
                'RDFOSBGR_P' => $row[89],
                'RDPVLA_PRR' => $row[90],
                'FTCYCLE_PR' => $row[91],
                'BRDGSTR_PR' => $row[92],
                'TRFSGN_PRR' => $row[93],
                'RDFOSBGR_R' => $row[94],
                'RDPVLA_RES' => $row[95],
                'FTCYCLE_RE' => $row[96],
                'BRDGSTR_RE' => $row[97],
                'TRFSGN_RES' => $row[98],
                'RDFOSBGR_U' => $row[99],
                'RDPVLA_USE' => $row[100],
                'FTCYCLE_US' => $row[101],
                'BRDGSTR_US' => $row[102],
                'TRFSGN_USE' => $row[103],
                'RDFOSBGR_A' => $row[104],
                'RDPVLA_AGE' => $row[105],
                'FTCYCLE_AG' => $row[106],
                'BRDGSTR_AG' => $row[107],
                'TRFSGN_AGE' => $row[108],
                'COMPAGEYEA' => $row[109],
                'USFLFEUNIT' => $row[110],
                'ID' => $row[111]
            ]);
        }
    }
}